/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.estruturadados.academia.ghrapic;

import com.estruturadados.academia.controller.CadastrarGraduacaoViewController;
import com.estruturadados.academia.database.model.Graduacao;
import com.estruturadados.academia.database.model.Modalidade;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastrarGraduacaoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroGraduacaoView
     */
    private Connection connection;
    private CadastrarGraduacaoViewController controller;
    private Graduacao graduacao;
    private boolean isEdicao;

    public CadastrarGraduacaoView(Connection connection, Graduacao graduacao) {
        initComponents();
        this.connection = connection;
        this.graduacao = graduacao;
        controller = new CadastrarGraduacaoViewController(connection);
        jComboBoxModalidades.removeAllItems();
        controller.carregarModalidades(jComboBoxModalidades);

        if (this.graduacao != null) {
            carregarDadosEdicao(this.graduacao);
        }

    }

    private void carregarDadosEdicao(Graduacao graduacao) {
        isEdicao = true;

        /*Não foi usado o comando abaixo pois não funcionou, mesmo quando tentado selecionar o objeto
          jComboBoxModalidades.setSelectedItem(graduacao.getModalidade().getModalidade());
         */
        for (int i = 0; i < jComboBoxModalidades.getItemCount(); i++) {
            if (jComboBoxModalidades.getItemAt(i).toString().equals(graduacao.getModalidade().getModalidade())) {
                jComboBoxModalidades.setSelectedIndex(i);
                break;
            }
        }
        jTextFieldGraduacao.setText(graduacao.getGraduacao());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelModalidade = new javax.swing.JLabel();
        jLabelGraduacao = new javax.swing.JLabel();
        jComboBoxModalidades = new javax.swing.JComboBox<>();
        jTextFieldGraduacao = new javax.swing.JTextField();
        jButtonGravar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setTitle("Cadastrar Graduação");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelModalidade.setText("Modalidade:");

        jLabelGraduacao.setText("Graduação:");

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModalidade)
                    .addComponent(jLabelGraduacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModalidade)
                    .addComponent(jComboBoxModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGraduacao)
                    .addComponent(jTextFieldGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGravar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:        
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldGraduacao.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor informe a graduação.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Graduacao graduacaoEditado = new Graduacao();
        graduacaoEditado.setModalidade(new Modalidade(jComboBoxModalidades.getSelectedItem().toString()));
        graduacaoEditado.setGraduacao(jTextFieldGraduacao.getText().trim());

        if (!isEdicao) {
            if (controller.inserirGraduacao(graduacaoEditado)) {
                JOptionPane.showMessageDialog(null, "Graduação cadastrada com sucesso.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar graduação.", "Atenção", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (controller.atualizarGraduacao(graduacao, graduacaoEditado)) {
                JOptionPane.showMessageDialog(null, "Graduação atualizada com sucesso.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao atualizar graduação.", "Atenção", JOptionPane.ERROR_MESSAGE);
            }
        }

        this.dispose();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JComboBox<Object> jComboBoxModalidades;
    private javax.swing.JLabel jLabelGraduacao;
    private javax.swing.JLabel jLabelModalidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldGraduacao;
    // End of variables declaration//GEN-END:variables
}
