/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.estruturadados.academia.ghrapic;

import com.estruturadados.academia.controller.CadastrarMatriculaViewController;
import com.estruturadados.academia.database.model.Aluno;
import com.estruturadados.academia.database.model.Matricula;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastrarMatriculaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarMatriculaView
     */
    private Connection connetion;
    private CadastrarMatriculaViewController controller;
    private Matricula matricula;
    private boolean isEdicao = false;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    public CadastrarMatriculaView(Connection connection, Matricula matricula) {
        initComponents();
        this.connetion = connetion;
        controller = new CadastrarMatriculaViewController(connection);
        this.matricula = matricula;
        controller.carregarAlunos(jComboBoxAlunos);
        txtDataMatricula.setText(sdf.format(new Date()));

        if (this.matricula != null) {
            carregarDadosEdicao(this.matricula);
        }
    }

    private void carregarDadosEdicao(Matricula matricula) {
        isEdicao = true;
        for (int i = 0; i < jComboBoxAlunos.getItemCount(); i++) {
            String text = jComboBoxAlunos.getItemAt(i).toString();
            if (matricula.getAluno().getAluno().equals(jComboBoxAlunos.getItemAt(i).toString())) {
                jComboBoxAlunos.setSelectedIndex(i);
                break;
            }
        }
        txtDataMatricula.setText(sdf.format(matricula.getDataMatricula()));
        jSpinnerDiaVencimento.setValue(matricula.getDiaVencimento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroMatricula = new javax.swing.JPanel();
        jPanelDadosDaMatricula = new javax.swing.JPanel();
        jLabelAluno = new javax.swing.JLabel();
        jComboBoxAlunos = new javax.swing.JComboBox<>();
        jLabelDataMatricula = new javax.swing.JLabel();
        txtDataMatricula = new javax.swing.JFormattedTextField();
        jLabelVencimento = new javax.swing.JLabel();
        jSpinnerDiaVencimento = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelModalidade = new javax.swing.JLabel();
        jComboBoxModalidades = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxGraduacoes = new javax.swing.JComboBox<>();
        jLabelPlano = new javax.swing.JLabel();
        jComboBoxPlanos = new javax.swing.JComboBox<>();
        jLabelDataInicio = new javax.swing.JLabel();
        txtInicioMatricula = new javax.swing.JFormattedTextField();
        btnCancelar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Matrícula");

        jPanelCadastroMatricula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelDadosDaMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da matrícula"));
        jPanelDadosDaMatricula.setToolTipText("Dados da matrícula");

        jLabelAluno.setText("Aluno:");

        jLabelDataMatricula.setText("Data matrícula:");

        try {
            txtDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelVencimento.setText("Vencimento:");

        jLabel2.setText("Data fim:");

        try {
            txtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFim.setEnabled(false);

        javax.swing.GroupLayout jPanelDadosDaMatriculaLayout = new javax.swing.GroupLayout(jPanelDadosDaMatricula);
        jPanelDadosDaMatricula.setLayout(jPanelDadosDaMatriculaLayout);
        jPanelDadosDaMatriculaLayout.setHorizontalGroup(
            jPanelDadosDaMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDaMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosDaMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDadosDaMatriculaLayout.createSequentialGroup()
                        .addComponent(jLabelAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosDaMatriculaLayout.createSequentialGroup()
                        .addComponent(jLabelVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerDiaVencimento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosDaMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataMatricula)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosDaMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDataMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtDataFim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDadosDaMatriculaLayout.setVerticalGroup(
            jPanelDadosDaMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDaMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosDaMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataMatricula)
                    .addComponent(txtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosDaMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVencimento)
                    .addComponent(jSpinnerDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modalidade"));

        jLabelModalidade.setText("Modalidade:");

        jLabel1.setText("Graduação:");

        jLabelPlano.setText("Plano:");

        jLabelDataInicio.setText("Data início:");

        try {
            txtInicioMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelModalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxGraduacoes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataInicio)
                    .addComponent(jLabelPlano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInicioMatricula)
                    .addComponent(jComboBoxPlanos, 0, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataInicio)
                        .addComponent(txtInicioMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelModalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxGraduacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlano)
                    .addComponent(jComboBoxPlanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroMatriculaLayout = new javax.swing.GroupLayout(jPanelCadastroMatricula);
        jPanelCadastroMatricula.setLayout(jPanelCadastroMatriculaLayout);
        jPanelCadastroMatriculaLayout.setHorizontalGroup(
            jPanelCadastroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDadosDaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroMatriculaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanelCadastroMatriculaLayout.setVerticalGroup(
            jPanelCadastroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosDaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGravar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(jSpinnerDiaVencimento.getValue().toString()) == 0) {
            JOptionPane.showMessageDialog(null, "Por favor informe o dia de vencimento.", "Atenção", JOptionPane.WARNING_MESSAGE);
            jSpinnerDiaVencimento.requestFocus();
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        Aluno aluno = (Aluno) jComboBoxAlunos.getSelectedItem();
        Matricula matriculaEditado = new Matricula();
        matriculaEditado.setAluno(aluno);
        try {
            matriculaEditado.setDataMatricula(sdf.parse(txtDataMatricula.getText()));
            matriculaEditado.setDiaVencimento(Integer.parseInt(jSpinnerDiaVencimento.getValue().toString()));

            if (!isEdicao) {
                if (controller.cadastrarMatricula(matriculaEditado)) {
                    JOptionPane.showMessageDialog(null, "Matricula cadastrada com sucesso.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar matrícula.", "Atenção", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                if (controller.atualizarMatricula(matricula, matriculaEditado)) {
                    JOptionPane.showMessageDialog(null, "Matricula atualizada com sucesso.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao atualizar matrícula.", "Atenção", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        this.dispose();
    }//GEN-LAST:event_btnGravarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<Object> jComboBoxAlunos;
    private javax.swing.JComboBox<Object> jComboBoxGraduacoes;
    private javax.swing.JComboBox<Object> jComboBoxModalidades;
    private javax.swing.JComboBox<Object> jComboBoxPlanos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAluno;
    private javax.swing.JLabel jLabelDataInicio;
    private javax.swing.JLabel jLabelDataMatricula;
    private javax.swing.JLabel jLabelModalidade;
    private javax.swing.JLabel jLabelPlano;
    private javax.swing.JLabel jLabelVencimento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastroMatricula;
    private javax.swing.JPanel jPanelDadosDaMatricula;
    private javax.swing.JSpinner jSpinnerDiaVencimento;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataMatricula;
    private javax.swing.JFormattedTextField txtInicioMatricula;
    // End of variables declaration//GEN-END:variables

}
